var Config = Config || {};

Config.version = '0.9 beta';

Config.whitelist = [
	'pokemonshowdown\\.com',
	'psim\\.us',
	'smogon\\.com',
	'upokecenter\\.com',
	'wikipedia\\.org',
	'wikimedia\\.org',
	'wiktionary\\.org',
	'github\\.com',
	'veekun\\.com',
	'bulbagarden\\.net',
	'serebii\\.net',
	'nuggetbridge\\.com',
	'reddit\\.com',
	'gamefaqs\\.com',
	'facebook\\.com',
	'twitter\\.com',
	'deviantart\\.com',
	'pokecommunity\\.com',
	'pokemonlab\\.com',
	'shoddybattle\\.com',
	'pokemon-online\\.eu',
	'pokecheck\\.org',
	'youtube\\.com',
	'challonge\\.com',
	'breakdown\\.forumotion\\.com',
	'pastebin\\.com',
	'hastebin\\.com',
	'piratepad\\.net',
	'trello\\.com',
	'thebattletower\\.no-ip\\.org',
	'meltsner\\.com',
	'guangcongluo\\.com',
	'cathyjf\\.com',
	'pokemonxy\\.com',
	'pokemon\\.com'
];

Config.customcolors = {
	'theimmortal': 'taco',
	'bmelts': 'testmelts',
	'zarel': 'aeo',
	'zarell': 'aeo',
	'greatsage': 'test454',
	'snowflakes': 'snowflake',
	'jumpluff': 'zacchaeus',
	'zacchaeus': 'jumpluff',
	'kraw': 'kraw1',
	'growlithe': 'steamroll',
	'snowflakes': 'endedinariot',
	'doomvendingmachine': 'theimmortal',
	'mikel': 'mikkel',
	'arcticblast': 'rsem',
	'mjb': 'thefourthchaser',
	'thefourthchaser': 'mjb',
	'tfc': 'mjb',
	'mikedecishere': 'mikedec3boobs',
	'heartsonfire': 'haatsuonfaiyaa',
	'limi': 'azure2',
	'haunter': 'cathy',
	'ginganinja': 'piratesandninjas',
	'aurora': 'c6n6fek',
	'solace': 'amorlan',
	'jdarden': 'dragonair',
	'queenofrandoms': 'hahaqor',
	'jelandee': 'ericbreviglieri',
	'diatom': 'dledledlewhooop',
	'waterbomb': 'wb0',
	'treecko': 'treee2222222',
	'treecko37': 'treee2222222',
	'violatic': 'violatic92',
	'exeggutor': 'ironmanatee',
	'ironmanatee': 'exeggutor',
	'shamethat': 'aaa10',
	'cathy': {color: '#ff5cb6'}
};
